name = "zenojunior"
workers_dev = true
main = ".output/server/index.mjs"
compatibility_date = "2022-04-07"

route = "zenojunior.com"

[site]
bucket = ".output/public"

[build]
command = "NITRO_PRESET=cloudflare yarn nuxt build"